/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.text.NumberFormat;
import java.util.ArrayList; 
import java.awt.Image;
import java.net.URL;
import javax.imageio.ImageIO;
/**
 *
 * @author thesmashburn
 */
public class MainFrame extends javax.swing.JFrame {
    public String addProductName;
    public int addProductId;
    public double addProductPrice;
    public String addProductVendor;
    public double addProductTax;
    public double addProductWeight;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        clearInputsCheckout();
        if (MarketPlaceDriver.mainSys.getUser() == null) {
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "card6");
        }
       // addAProductWarning.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        homeContainer = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        checkoutButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        homeHeader = new javax.swing.JLabel();
        homeNoticeLabel = new javax.swing.JLabel();
        homeReportButton = new javax.swing.JButton();
        homeManagementButton = new javax.swing.JButton();
        homeNameLabel = new javax.swing.JLabel();
        addContainer = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        addHeaderLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addNameField = new javax.swing.JTextField();
        addPriceField = new javax.swing.JTextField();
        addVendorField = new javax.swing.JTextField();
        addTaxField = new javax.swing.JTextField();
        addWeightField = new javax.swing.JTextField();
        addNoticeLabel = new javax.swing.JLabel();
        updateContainer = new javax.swing.JPanel();
        submitButtonUpd = new javax.swing.JButton();
        backButtonUpd = new javax.swing.JButton();
        updateHeader = new javax.swing.JLabel();
        updateSearchField = new javax.swing.JTextField();
        updateFindLabel = new javax.swing.JLabel();
        updateSearchButton = new javax.swing.JButton();
        updateErrorLabel = new javax.swing.JLabel();
        updateWeightField = new javax.swing.JTextField();
        updatePriceField = new javax.swing.JTextField();
        updateVendorField = new javax.swing.JTextField();
        updateNameField = new javax.swing.JTextField();
        updateTaxField = new javax.swing.JTextField();
        updateNameLabel = new javax.swing.JLabel();
        updatePriceLabel = new javax.swing.JLabel();
        updateVendorLabel = new javax.swing.JLabel();
        updateTaxLabel = new javax.swing.JLabel();
        updateWeightLabel = new javax.swing.JLabel();
        checkoutContainer = new javax.swing.JPanel();
        submitButtonCheck = new javax.swing.JButton();
        backButtonCheck = new javax.swing.JButton();
        nameScroll = new javax.swing.JScrollPane();
        nameList = new javax.swing.JList<>();
        checkAddItem = new javax.swing.JLabel();
        checkProductIDLabel = new javax.swing.JLabel();
        checkQuantityLabel = new javax.swing.JLabel();
        checkHead = new javax.swing.JLabel();
        productIDField = new javax.swing.JTextField();
        quantityField = new javax.swing.JTextField();
        checkName = new javax.swing.JLabel();
        checkQuantity = new javax.swing.JLabel();
        checkPrice = new javax.swing.JLabel();
        quantityScroll = new javax.swing.JScrollPane();
        quantityList = new javax.swing.JList<>();
        priceScroll = new javax.swing.JScrollPane();
        priceList = new javax.swing.JList<>();
        checkoutAddButton = new javax.swing.JButton();
        checkSubLabel = new javax.swing.JLabel();
        checkTotalLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        errorLabelCheckout = new javax.swing.JLabel();
        loginContainer = new javax.swing.JPanel();
        loginHeader = new javax.swing.JLabel();
        loginNameLabel = new javax.swing.JLabel();
        loginPassLabel = new javax.swing.JLabel();
        loginPassField = new javax.swing.JPasswordField();
        loginNameField = new javax.swing.JTextField();
        loginSubmitButton = new javax.swing.JButton();
        loginNoticeLabel = new javax.swing.JLabel();
        settingsContainer = new javax.swing.JPanel();
        settingsHeader = new javax.swing.JLabel();
        settingsProfileLabel = new javax.swing.JLabel();
        settingsPasswordLabel = new javax.swing.JLabel();
        settingsProfileField = new javax.swing.JTextField();
        settingsPasswordField = new javax.swing.JPasswordField();
        settingUpdateButton = new javax.swing.JButton();
        settingsBackButton = new javax.swing.JButton();
        settingsNoticeLabel = new javax.swing.JLabel();
        settingsProfilePic = new javax.swing.JLabel();
        settingsProfilePicLabel = new javax.swing.JLabel();
        usersContainer = new javax.swing.JPanel();
        usersHeaderLabel = new javax.swing.JLabel();
        usersSubmitButton = new javax.swing.JButton();
        usersBackButton = new javax.swing.JButton();
        usersNameField = new javax.swing.JTextField();
        usersProfilePicField = new javax.swing.JTextField();
        usersDisclaimerLabel = new javax.swing.JLabel();
        usersNameLabel = new javax.swing.JLabel();
        usersProfilePicLabel = new javax.swing.JLabel();
        usersManagerCheck = new javax.swing.JCheckBox();
        userNoticeLabel = new javax.swing.JLabel();
        reportContainer = new javax.swing.JPanel();
        reportHeaderLabel = new javax.swing.JLabel();
        reportBackButton = new javax.swing.JButton();
        reportNamePane = new javax.swing.JScrollPane();
        reportProductName = new javax.swing.JList<>();
        reportSalePane = new javax.swing.JScrollPane();
        reportProductSale = new javax.swing.JList<>();
        reportRevenuePane = new javax.swing.JScrollPane();
        reportProductRevenue = new javax.swing.JList<>();
        reportIDPane = new javax.swing.JScrollPane();
        reportProductID = new javax.swing.JList<>();
        reportSortSelect = new javax.swing.JComboBox<>();
        reportRevenueLabel = new javax.swing.JLabel();
        reportRevenueValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        addButton.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        addButton.setText("Add Product");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        checkoutButton.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        checkoutButton.setText("Checkout");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        updateButton.setText("Update Product");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        homeHeader.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        homeHeader.setText("Welcome to MarketPlace!");

        homeNoticeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        homeReportButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        homeReportButton.setText("Business Report");
        homeReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeReportButtonActionPerformed(evt);
            }
        });

        homeManagementButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        homeManagementButton.setText("User Management");
        homeManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeManagementButtonActionPerformed(evt);
            }
        });

        homeNameLabel.setText("jLabel1");
        homeNameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeNameLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout homeContainerLayout = new javax.swing.GroupLayout(homeContainer);
        homeContainer.setLayout(homeContainerLayout);
        homeContainerLayout.setHorizontalGroup(
            homeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeContainerLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(homeNoticeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeHeader)
                .addGap(79, 79, 79)
                .addComponent(homeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(homeContainerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(homeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeContainerLayout.createSequentialGroup()
                        .addGroup(homeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homeContainerLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(checkoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(homeContainerLayout.createSequentialGroup()
                                .addComponent(homeReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(homeContainerLayout.createSequentialGroup()
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
        );
        homeContainerLayout.setVerticalGroup(
            homeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeContainerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(homeHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeContainerLayout.createSequentialGroup()
                        .addComponent(checkoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeContainerLayout.createSequentialGroup()
                        .addComponent(homeManagementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(homeNoticeLabel)
                .addGap(36, 36, 36))
            .addGroup(homeContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(homeContainer, "card3");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        addHeaderLabel.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        addHeaderLabel.setText("Add Product");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Price");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel3.setText("Vendor");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("Weight");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel5.setText("Tax");

        addNoticeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        addNoticeLabel.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout addContainerLayout = new javax.swing.GroupLayout(addContainer);
        addContainer.setLayout(addContainerLayout);
        addContainerLayout.setHorizontalGroup(
            addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addContainerLayout.createSequentialGroup()
                        .addComponent(submitButton)
                        .addGap(18, 18, 18)
                        .addComponent(backButton)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addContainerLayout.createSequentialGroup()
                        .addComponent(addHeaderLabel)
                        .addGap(257, 257, 257))))
            .addGroup(addContainerLayout.createSequentialGroup()
                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addContainerLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(addContainerLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addWeightField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addContainerLayout.createSequentialGroup()
                                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(24, 24, 24)
                                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(addPriceField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addContainerLayout.createSequentialGroup()
                                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addTaxField)
                                    .addComponent(addVendorField)))))
                    .addGroup(addContainerLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(addNoticeLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addContainerLayout.setVerticalGroup(
            addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addContainerLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(addHeaderLabel)
                .addGap(76, 76, 76)
                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addVendorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addComponent(addNoticeLabel)
                .addGap(23, 23, 23)
                .addGroup(addContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(backButton))
                .addGap(20, 20, 20))
        );

        mainPanel.add(addContainer, "card2");

        submitButtonUpd.setText("Submit");
        submitButtonUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonUpdActionPerformed(evt);
            }
        });

        backButtonUpd.setText("Back");
        backButtonUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonUpdActionPerformed(evt);
            }
        });

        updateHeader.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        updateHeader.setText("Update Product");

        updateFindLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        updateFindLabel.setText("Find Product by ID:");

        updateSearchButton.setText("Search");
        updateSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSearchButtonActionPerformed(evt);
            }
        });

        updateErrorLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        updateErrorLabel.setForeground(new java.awt.Color(255, 51, 51));

        updateNameLabel.setText("Name:");

        updatePriceLabel.setText("Price:");

        updateVendorLabel.setText("Vendor");

        updateTaxLabel.setText("Tax");

        updateWeightLabel.setText("Weight");

        javax.swing.GroupLayout updateContainerLayout = new javax.swing.GroupLayout(updateContainer);
        updateContainer.setLayout(updateContainerLayout);
        updateContainerLayout.setHorizontalGroup(
            updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateContainerLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(updateHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateContainerLayout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatePriceLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateNameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateVendorLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateContainerLayout.createSequentialGroup()
                            .addComponent(submitButtonUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(backButtonUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateContainerLayout.createSequentialGroup()
                            .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(updateContainerLayout.createSequentialGroup()
                                    .addComponent(updatePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updateWeightLabel))
                                .addComponent(updateFindLabel)
                                .addGroup(updateContainerLayout.createSequentialGroup()
                                    .addComponent(updateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updateTaxLabel)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(updateErrorLabel)
                                .addGroup(updateContainerLayout.createSequentialGroup()
                                    .addComponent(updateSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(updateSearchButton))
                                .addComponent(updateWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(updateTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(125, 125, 125)))
                    .addComponent(updateVendorField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        updateContainerLayout.setVerticalGroup(
            updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateContainerLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(updateHeader)
                .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateContainerLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(updateFindLabel))
                    .addGroup(updateContainerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateNameLabel)
                    .addComponent(updateTaxLabel))
                .addGap(34, 34, 34)
                .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePriceLabel)
                    .addComponent(updateWeightLabel))
                .addGap(33, 33, 33)
                .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateVendorField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateVendorLabel))
                .addGap(45, 45, 45)
                .addGroup(updateContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButtonUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButtonUpd, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        mainPanel.add(updateContainer, "card4");

        submitButtonCheck.setText("Finish");
        submitButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonCheckActionPerformed(evt);
            }
        });

        backButtonCheck.setText("Back");
        backButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonCheckActionPerformed(evt);
            }
        });

        nameList.setModel(new DefaultListModel());
        nameScroll.setViewportView(nameList);

        checkAddItem.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        checkAddItem.setText("Add an Item");

        checkProductIDLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        checkProductIDLabel.setText("Prodcut ID");

        checkQuantityLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        checkQuantityLabel.setText("Quantity");

        checkHead.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        checkHead.setText("Checkout");

        checkName.setText("Name");

        checkQuantity.setText("Quantity");

        checkPrice.setText("Price");

        quantityList.setModel(new DefaultListModel());
        quantityScroll.setViewportView(quantityList);

        priceList.setModel(new DefaultListModel());
        priceScroll.setViewportView(priceList);

        checkoutAddButton.setText("Add Item");
        checkoutAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutAddButtonActionPerformed(evt);
            }
        });

        checkSubLabel.setText("Sub-Total:");

        checkTotalLabel.setText("Total:");

        errorLabelCheckout.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout checkoutContainerLayout = new javax.swing.GroupLayout(checkoutContainer);
        checkoutContainer.setLayout(checkoutContainerLayout);
        checkoutContainerLayout.setHorizontalGroup(
            checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutContainerLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkSubLabel)
                    .addComponent(checkTotalLabel))
                .addGap(29, 29, 29)
                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalLabel)
                    .addComponent(subtotalLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(checkoutContainerLayout.createSequentialGroup()
                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkoutContainerLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(checkHead))
                    .addGroup(checkoutContainerLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(checkoutContainerLayout.createSequentialGroup()
                                .addComponent(checkName)
                                .addGap(63, 63, 63)
                                .addComponent(checkQuantity)
                                .addGap(18, 18, 18))
                            .addGroup(checkoutContainerLayout.createSequentialGroup()
                                .addComponent(nameScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quantityScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGap(1, 1, 1)
                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(checkoutContainerLayout.createSequentialGroup()
                                .addComponent(priceScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(checkoutContainerLayout.createSequentialGroup()
                                        .addGap(317, 317, 317)
                                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkProductIDLabel)
                                            .addComponent(checkQuantityLabel)
                                            .addComponent(submitButtonCheck))
                                        .addGap(18, 18, 18)
                                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(productIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                            .addComponent(quantityField)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutContainerLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(backButtonCheck))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutContainerLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkoutAddButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutContainerLayout.createSequentialGroup()
                                                .addComponent(errorLabelCheckout)
                                                .addGap(77, 77, 77))))))
                            .addGroup(checkoutContainerLayout.createSequentialGroup()
                                .addComponent(checkPrice)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutContainerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkAddItem)))
                .addGap(50, 50, 50))
        );
        checkoutContainerLayout.setVerticalGroup(
            checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutContainerLayout.createSequentialGroup()
                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkoutContainerLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(checkHead)
                        .addGap(38, 38, 38)
                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkName)
                            .addComponent(checkQuantity)
                            .addComponent(checkPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(checkoutContainerLayout.createSequentialGroup()
                                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkProductIDLabel)
                                    .addComponent(productIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(checkQuantityLabel)
                                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkoutAddButton)
                                .addGap(18, 18, 18)
                                .addComponent(errorLabelCheckout))
                            .addComponent(quantityScroll)
                            .addComponent(priceScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                            .addComponent(nameScroll)))
                    .addGroup(checkoutContainerLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(checkAddItem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutContainerLayout.createSequentialGroup()
                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkSubLabel)
                            .addComponent(subtotalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkTotalLabel)
                            .addComponent(totalLabel))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkoutContainerLayout.createSequentialGroup()
                        .addGroup(checkoutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitButtonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backButtonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
        );

        mainPanel.add(checkoutContainer, "card5");

        loginHeader.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        loginHeader.setText("MarketPlace Login");

        loginNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        loginNameLabel.setText("Username:");

        loginPassLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        loginPassLabel.setText("Password:");

        loginNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginNameFieldActionPerformed(evt);
            }
        });

        loginSubmitButton.setText("Submit");
        loginSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSubmitButtonActionPerformed(evt);
            }
        });

        loginNoticeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        loginNoticeLabel.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout loginContainerLayout = new javax.swing.GroupLayout(loginContainer);
        loginContainer.setLayout(loginContainerLayout);
        loginContainerLayout.setHorizontalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginContainerLayout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginContainerLayout.createSequentialGroup()
                        .addComponent(loginNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginHeader)
                    .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(loginSubmitButton)
                        .addGroup(loginContainerLayout.createSequentialGroup()
                            .addComponent(loginPassLabel)
                            .addGap(18, 18, 18)
                            .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(loginNoticeLabel)
                                .addComponent(loginPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(157, 157, 157))
        );
        loginContainerLayout.setVerticalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(loginHeader)
                .addGap(150, 150, 150)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginNameLabel)
                    .addComponent(loginNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginPassLabel)
                    .addComponent(loginPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(loginSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(loginNoticeLabel)
                .addGap(54, 54, 54))
        );

        mainPanel.add(loginContainer, "card6");

        settingsHeader.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        settingsHeader.setText("User Settings");

        settingsProfileLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        settingsProfileLabel.setText("Profile Picture URL:");

        settingsPasswordLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        settingsPasswordLabel.setText("Password:");

        settingUpdateButton.setText("Update");
        settingUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingUpdateButtonActionPerformed(evt);
            }
        });

        settingsBackButton.setText("Back");
        settingsBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBackButtonActionPerformed(evt);
            }
        });

        settingsNoticeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        settingsNoticeLabel.setForeground(new java.awt.Color(255, 51, 51));

        settingsProfilePicLabel.setText("Current Profile Picture");

        javax.swing.GroupLayout settingsContainerLayout = new javax.swing.GroupLayout(settingsContainer);
        settingsContainer.setLayout(settingsContainerLayout);
        settingsContainerLayout.setHorizontalGroup(
            settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsContainerLayout.createSequentialGroup()
                .addGroup(settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, settingsContainerLayout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(settingsContainerLayout.createSequentialGroup()
                                .addComponent(settingsProfileLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(settingsProfileField, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(settingsContainerLayout.createSequentialGroup()
                                .addComponent(settingsPasswordLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(settingsPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(settingsNoticeLabel))
                        .addGap(0, 25, Short.MAX_VALUE))
                    .addGroup(settingsContainerLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(settingsHeader)
                        .addGap(167, 167, 167))
                    .addGroup(settingsContainerLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(settingsProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(settingUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(settingsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGap(59, 59, 59))
            .addGroup(settingsContainerLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(settingsProfilePicLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        settingsContainerLayout.setVerticalGroup(
            settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsContainerLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(settingsHeader)
                .addGap(118, 118, 118)
                .addGroup(settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsProfileLabel)
                    .addComponent(settingsProfileField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingsPasswordLabel)
                    .addComponent(settingsPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingsProfilePicLabel)
                .addGroup(settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingsContainerLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(settingsNoticeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(settingsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(settingUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(settingsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(settingsContainerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(settingsProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
        );

        mainPanel.add(settingsContainer, "card7");

        usersHeaderLabel.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        usersHeaderLabel.setText("Create New User");

        usersSubmitButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        usersSubmitButton.setText("Create");
        usersSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersSubmitButtonActionPerformed(evt);
            }
        });

        usersBackButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        usersBackButton.setText("Back");
        usersBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersBackButtonActionPerformed(evt);
            }
        });

        usersDisclaimerLabel.setText("*note that the password will be set to password by default");

        usersNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        usersNameLabel.setText("Username");

        usersProfilePicLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        usersProfilePicLabel.setText("Profile Picture URL");

        usersManagerCheck.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        usersManagerCheck.setText("Manager");

        userNoticeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        userNoticeLabel.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout usersContainerLayout = new javax.swing.GroupLayout(usersContainer);
        usersContainer.setLayout(usersContainerLayout);
        usersContainerLayout.setHorizontalGroup(
            usersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersContainerLayout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(userNoticeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(usersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usersDisclaimerLabel)
                    .addGroup(usersContainerLayout.createSequentialGroup()
                        .addGroup(usersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usersHeaderLabel)
                            .addComponent(usersSubmitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(usersBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
            .addGroup(usersContainerLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(usersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usersManagerCheck)
                    .addGroup(usersContainerLayout.createSequentialGroup()
                        .addGroup(usersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usersProfilePicLabel)
                            .addComponent(usersNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(usersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usersNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(usersProfilePicField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        usersContainerLayout.setVerticalGroup(
            usersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersContainerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(usersHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usersDisclaimerLabel)
                .addGap(41, 41, 41)
                .addGroup(usersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usersNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usersNameLabel))
                .addGap(18, 18, 18)
                .addGroup(usersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usersProfilePicField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usersProfilePicLabel))
                .addGap(56, 56, 56)
                .addComponent(usersManagerCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addGroup(usersContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usersBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usersSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNoticeLabel))
                .addGap(55, 55, 55))
        );

        mainPanel.add(usersContainer, "card8");

        reportHeaderLabel.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        reportHeaderLabel.setText("Business Report");

        reportBackButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        reportBackButton.setText("Back");
        reportBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportBackButtonActionPerformed(evt);
            }
        });

        reportNamePane.setViewportView(reportProductName);

        reportSalePane.setViewportView(reportProductSale);

        reportRevenuePane.setViewportView(reportProductRevenue);

        reportIDPane.setViewportView(reportProductID);

        reportSortSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name", "Number Sold", "Revenue" }));
        reportSortSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportSortSelectActionPerformed(evt);
            }
        });

        reportRevenueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        reportRevenueLabel.setText("Total Revenue");

        reportRevenueValue.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

        javax.swing.GroupLayout reportContainerLayout = new javax.swing.GroupLayout(reportContainer);
        reportContainer.setLayout(reportContainerLayout);
        reportContainerLayout.setHorizontalGroup(
            reportContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportContainerLayout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(reportHeaderLabel)
                .addGap(185, 185, 185))
            .addGroup(reportContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reportIDPane, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(reportContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportContainerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(reportNamePane, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reportSalePane, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reportRevenuePane, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(reportContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reportContainerLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reportBackButton)
                                .addGap(25, 25, 25))
                            .addGroup(reportContainerLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(reportRevenueValue)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(reportContainerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(reportContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reportSortSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportRevenueLabel))
                        .addGap(91, 91, 91))))
        );
        reportContainerLayout.setVerticalGroup(
            reportContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportContainerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(reportHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reportSortSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reportContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportContainerLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(reportRevenueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reportRevenueValue)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                        .addComponent(reportBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(reportContainerLayout.createSequentialGroup()
                        .addGroup(reportContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(reportRevenuePane, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                            .addComponent(reportSalePane)
                            .addComponent(reportNamePane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reportIDPane, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        mainPanel.add(reportContainer, "card9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 821, 644);
    }// </editor-fold>//GEN-END:initComponents

     // Submit button -> add product
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        Boolean valid = false;
        String name = "";
        String vendor = "";
        double weight = 0;
        double tax = 0;
        double price = 0;
        if (correctString(addNameField.getText())) {
            name = addNameField.getText();
             if (correctString(addVendorField.getText())) {
                 vendor = addVendorField.getText();
                 if (isDouble(addWeightField.getText())) {
                     weight = Double.parseDouble(addWeightField.getText());
                     if (isDouble(addTaxField.getText())) {
                         tax = Double.parseDouble(addTaxField.getText());
                         if (isDouble(addPriceField.getText())) {
                             price = Double.parseDouble(addPriceField.getText());
                             valid = true;
                         }
                     }
                 }
             }  
        }
        
        if (valid) {
            MarketPlaceDriver.mainSys.pushAddProduct(name, price, vendor, tax, weight);
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "card3");
            
            homeNoticeLabel.setText("Product Sucessfully Added!");
            
        }
        else addNoticeLabel.setText("*Check types of inputs.");
       
        
      /*  if (verifyNewProduct(productNameField.getText(), productIdField.getText(), productPriceField.getText(), productVendorField.getText(), productTaxField.getText(), productWeightField.getText())) {
            
            Boolean added = DataBaseManager.addProduct(addProductName, addProductId, addProductPrice, addProductVendor, addProductTax, addProductWeight);
            
            if (added) {
                CardLayout card = (CardLayout)mainPanel.getLayout();
                card.show(mainPanel, "card3");
                homeNoticeLabel.setText("Product succesfully added!");
                addInputsReset();
                MarketPlaceDriver.mainSys.updateLists();
            }
            
            else {
               CardLayout card = (CardLayout)mainPanel.getLayout();
               card.show(mainPanel, "card3");
                homeNoticeLabel.setText("Product failed to be added");
            }
            
            /*JDialog successDialog = new JDialog();
            successDialog.setTitle("Success");
            successDialog.setSize(200, 200);
        }
        else {  
            
            // Display warning
            return;
        }*/
      
    }//GEN-LAST:event_submitButtonActionPerformed
    
     /* THIS IS THE SECTION FOR EVENTS RELATED EVENTS*/
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        clearAddInputs();
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card2");
    }//GEN-LAST:event_addButtonActionPerformed
    
     
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card3");
    }//GEN-LAST:event_backButtonActionPerformed

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        clearInputsCheckout();
        MarketPlaceDriver.mainSys.checkoutOrder();
        card.show(mainPanel, "card5");
    }//GEN-LAST:event_checkoutButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        changeInputsUpdate(false);
        card.show(mainPanel, "card4");
    }//GEN-LAST:event_updateButtonActionPerformed

    private void backButtonUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonUpdActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card3");
        
    }//GEN-LAST:event_backButtonUpdActionPerformed

    
    private void backButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonCheckActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card3");
    }//GEN-LAST:event_backButtonCheckActionPerformed

    /*This is the code for the checkout add item button*/
    private void checkoutAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutAddButtonActionPerformed
        // TODO add your handling code here:
        errorLabelCheckout.setText("");
        NumberFormat formatter = NumberFormat.getCurrencyInstance();
       
        if (!isInteger(productIDField.getText()) || !isInteger(quantityField.getText())) errorLabelCheckout.setText("*Fields must be Integers");
        else if (Integer.parseInt(quantityField.getText()) < 1) errorLabelCheckout.setText("*Quantity must be greater than 0");
        else {
            int productID = Integer.parseInt(productIDField.getText());
            int quantity = Integer.parseInt(quantityField.getText());
            CheckoutItem temp = MarketPlaceDriver.mainSys.addItemToCheckout(productID, quantity);
            if (temp.getID() != 0) {
                DefaultListModel nameModel = (DefaultListModel) nameList.getModel();
                DefaultListModel quanModel = (DefaultListModel) quantityList.getModel();
                DefaultListModel totalModel = (DefaultListModel) priceList.getModel();
                
                nameModel.addElement(temp.getName());
                quanModel.addElement(temp.getQuantity());
                totalModel.addElement(temp.getPrice());
                
                totalLabel.setText(formatter.format(MarketPlaceDriver.mainSys.getCurrentTotal()));
                subtotalLabel.setText(formatter.format(MarketPlaceDriver.mainSys.getCurrentSubTotal()));
            }
            else errorLabelCheckout.setText("*Product not found");
        }
        
    }//GEN-LAST:event_checkoutAddButtonActionPerformed

    private void submitButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonCheckActionPerformed
        // TODO add your handling code here:
        if (MarketPlaceDriver.mainSys.getCurrentCount() >= 1) {
            if (MarketPlaceDriver.mainSys.pushCurrentCheckoutOrder()) {
                CardLayout card = (CardLayout)mainPanel.getLayout();
                card.show(mainPanel, "card3");
                homeNoticeLabel.setText("Order sucessfully processed!");
                MarketPlaceDriver.mainSys.updateLists();
            }
            else errorLabelCheckout.setText("Problem connecting to server");
        }
        else errorLabelCheckout.setText("Must add items to cart");
    }//GEN-LAST:event_submitButtonCheckActionPerformed

    private void updateSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSearchButtonActionPerformed
        // TODO add your handling code here:
        updateErrorLabel.setText("");
        if (isInteger(updateSearchField.getText())) {
            int productID = Integer.parseInt(updateSearchField.getText());
            Product temp = MarketPlaceDriver.mainSys.findProductUpdate(productID);
            if (temp.getID() != 0) {
                updateNameField.setText(temp.getName());
                updatePriceField.setText(temp.getPrice() + "");
                updateVendorField.setText(temp.getVendor());
                updateTaxField.setText(temp.getTax() + "");
                updateWeightField.setText(temp.getWeight() + "");
                changeInputsUpdate(true);
            }
            else {
                updateErrorLabel.setText("*Product not found");
                changeInputsUpdate(false);
            }
        }
        else {
            updateErrorLabel.setText("*Invalid ID format");
            changeInputsUpdate(false);
        }
        
    }//GEN-LAST:event_updateSearchButtonActionPerformed

    private void submitButtonUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonUpdActionPerformed
        // TODO add your handling code here:
        Boolean priceBool = isDouble(updatePriceField.getText());
        Boolean taxBool = isDouble(updateTaxField.getText());
        Boolean weightBool = isDouble(updateWeightField.getText());
        Boolean nameBool = correctString(updateNameField.getText());
        Boolean vendorBool = correctString(updateVendorField.getText());
        if (!priceBool || !taxBool || !weightBool || !nameBool || !vendorBool) {
            updateErrorLabel.setText("*Incorrect format for given field(s)");
        }
        else {
            double price = Double.parseDouble(updatePriceField.getText());
            double tax = Double.parseDouble(updateTaxField.getText());
            double weight = Double.parseDouble(updateWeightField.getText());
            String name = updateNameField.getText();
            String vendor = updateVendorField.getText();
            
            if (MarketPlaceDriver.mainSys.pushProductUpdate(name, price, vendor, tax, weight)) {
                CardLayout card = (CardLayout)mainPanel.getLayout();
                card.show(mainPanel, "card3");
                homeNoticeLabel.setText("Product succesfully updated!");
            }
        }
        
    }//GEN-LAST:event_submitButtonUpdActionPerformed

    private void loginNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginNameFieldActionPerformed

    private void loginSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSubmitButtonActionPerformed
        // TODO add your handling code here:
        String username = loginNameField.getText();
        char[] passwordChar = loginPassField.getPassword();
        String password = new String(passwordChar);
        
        if (MarketPlaceDriver.mainSys.authenticateUser(username, password)) {
             CardLayout card = (CardLayout)mainPanel.getLayout();
             card.show(mainPanel, "card3");
             homeNameLabel.setText(username);
             
             if (!MarketPlaceDriver.mainSys.isAdmin()) {
                 //setvisibility
                 homeReportButton.setVisible(false);
                 homeManagementButton.setVisible(false);
                 updateButton.setVisible(false);
                 addButton.setVisible(false);
             }
             
             //Set Profile Picture
              try {
                User mainuser = MarketPlaceDriver.mainSys.getUser();
                URL url = new URL(mainuser.getProfilePic());
                Image image = ImageIO.read(url);
                Image resizedImage =  image.getScaledInstance(homeNameLabel.getWidth(), homeNameLabel.getHeight(), 1);
                homeNameLabel.setIcon(new ImageIcon(resizedImage));
        } catch (Exception e) {
            
        }
             
             
             
             
        }
        else {
            loginNoticeLabel.setText("Incorrect login.");
        }
       
        
    }//GEN-LAST:event_loginSubmitButtonActionPerformed

    private void homeNameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeNameLabelMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card7");
        try {
            User mainuser = MarketPlaceDriver.mainSys.getUser();
            URL url = new URL(mainuser.getProfilePic());
            Image image = ImageIO.read(url);
            Image resizedImage =  image.getScaledInstance(settingsProfilePic.getWidth(), settingsProfilePic.getHeight(), 1);
   
            settingsProfilePic.setIcon(new ImageIcon(resizedImage));
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_homeNameLabelMouseClicked

    private void homeManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeManagementButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card8");
    }//GEN-LAST:event_homeManagementButtonActionPerformed

    private void homeReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeReportButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card9");
        populateReport();
        
        
         
    }//GEN-LAST:event_homeReportButtonActionPerformed

    private void settingsBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBackButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card3");
    }//GEN-LAST:event_settingsBackButtonActionPerformed

    private void settingUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingUpdateButtonActionPerformed
        // TODO add your handling code here:
        //Update the current user information as well as the profile pcture field and the names and such.
        String profilePic = settingsProfileField.getText();
        char[] passwordChar = settingsPasswordField.getPassword();
        String password = new String(passwordChar);
        Boolean valid = false;
        User mainuser = MarketPlaceDriver.mainSys.getUser();
        
        try {
            URL testURL = new URL(profilePic);
        } catch (Exception e) {
            
            if (profilePic.equals("")) {
                profilePic = mainuser.getProfilePic();
                valid = true;
                if (password.equals("")) password = mainuser.getPassword();
            }
            else settingsNoticeLabel.setText("*Not a valid URL.");
            
        }
        
        if (valid){
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "card3");
            MarketPlaceDriver.mainSys.pushUpdateUser(mainuser.getName(), profilePic, password);
            try {
            
            URL url = new URL(mainuser.getProfilePic());
            Image image = ImageIO.read(url);
            Image resizedImage =  image.getScaledInstance(homeNameLabel.getWidth(), homeNameLabel.getHeight(), 1);
   
            homeNameLabel.setIcon(new ImageIcon(resizedImage));
        } catch (Exception e) {
            
        }
            homeNoticeLabel.setText("Settings Updated!");
        }
        
        
        
    }//GEN-LAST:event_settingUpdateButtonActionPerformed

    private void usersSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersSubmitButtonActionPerformed
        // TODO add your handling code here:
        //do te routine check for correct fields of this user then make sure to assign default pw.
        String username = usersNameField.getText();
        Boolean exists = false;
        ArrayList<User> currentUserList = MarketPlaceDriver.mainSys.getCurrentUserList();
        for (User user : currentUserList) {
            if ((user.getName().toLowerCase()).equals(username.toLowerCase())) {
                exists = true;
                break;
            }
        }
        
        if (!exists) {
            String profilepic = "https://www.drupal.org/files/issues/default-avatar.png";
            int usertype = 2;
            String password = "password";
            if (usersProfilePicField.getText() != "") profilepic = usersProfilePicField.getText();
            if (usersManagerCheck.isSelected()) usertype = 1;
            DataBaseManager.addUser(username, password, profilepic, usertype);
            
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "card3");
            homeNoticeLabel.setText("User Succesfully Added!");
        }
        else userNoticeLabel.setText("*User already exists");
        
    }//GEN-LAST:event_usersSubmitButtonActionPerformed

    private void usersBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersBackButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card3");
        homeNoticeLabel.setText("");
    }//GEN-LAST:event_usersBackButtonActionPerformed

    private void reportBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBackButtonActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "card3");
        homeNoticeLabel.setText("");
    }//GEN-LAST:event_reportBackButtonActionPerformed

    private void reportSortSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportSortSelectActionPerformed
        // TODO add your handling code here:
        //When someone change sthe sort method of the business report.
        clearInputsCheckout();
        populateReport();
    }//GEN-LAST:event_reportSortSelectActionPerformed
    
    
     /* THIS IS THE SECTION FOR GENERAL METHODS */
    
    public void populateReport() {
        double totalRevenue = 0;
         NumberFormat formatter = NumberFormat.getCurrencyInstance();
        //Time to initiate this bitch
       // ArrayList<Product> productList = MarketPlaceDriver.mainSys.getCurrentProductList();
        //Sort based on the thing
        String sortValue = reportSortSelect.getSelectedItem().toString();
        ArrayList<Product> productList = MarketPlaceDriver.mainSys.getSortedProducts(sortValue);
        DefaultListModel idModel = (DefaultListModel) reportProductID.getModel();
        DefaultListModel nameModel = (DefaultListModel) reportProductName.getModel();
        DefaultListModel quanModel = (DefaultListModel) reportProductSale.getModel();
        DefaultListModel revModel = (DefaultListModel) reportProductRevenue.getModel();
        for (Product product : productList) {
           
            idModel.addElement(product.getID());
            nameModel.addElement(product.getName());
            quanModel.addElement(product.getNumberSold());
            revModel.addElement(formatter.format(product.getRevenue()));
            totalRevenue += product.getRevenue();
            
        }
        String formattedTotal = formatter.format(totalRevenue);
        reportRevenueValue.setText(formattedTotal);
    }

    /*  public boolean verifyNewProduct(String nameIn, String idIn, String priceIn, String vendorIn, String taxIn, String weightIn) {
        
        try {
            addProductId = Integer.parseInt(idIn);
            addProductPrice = Double.parseDouble(priceIn);
            addProductTax = Double.parseDouble(taxIn);
            addProductWeight = Double.parseDouble(weightIn);
        } catch (NumberFormatException e) {
            addAProductWarning.setVisible(true);
            return false;
        }
        Product prod = MarketPlaceDriver.mainSys.findProductUpdate(addProductId);
        if (nameIn == null || idIn == null || priceIn == null || vendorIn == null || taxIn == null || weightIn == null) {
            addAProductWarning.setVisible(true);
            addAProductWarning.setText("* Re-evaluate fields");
            return false;
        }
        else if (prod.getID() != 0) {
            addAProductWarning.setVisible(true);
            addAProductWarning.setText("* Product with the ID already exists");
            return false;
        }
        
            addProductName = nameIn;
            addProductVendor = vendorIn;
            
        return true;
    }*/
    
    public Boolean isInteger(String str) {
        try {
        Integer.parseInt(str);
        return true;
    } catch (NumberFormatException nfe) {
        return false;
    } 
    }
    
    public Boolean isDouble(String str) {
        try {
        Double.parseDouble(str);
        return true;
    } catch (Exception nfe) {
        return false;
    } 
    }
    
    public Boolean correctString(String str) {
        try {
            if (str.trim().length() > 0) return true;
            else return false;
        } catch (Exception e) {
            return false;
        }
    }
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    public void clearAddInputs() {
        addNameField.setText("");
        addVendorField.setText("");
        addTaxField.setText("");
        addPriceField.setText("");
        addWeightField.setText("");
        addNoticeLabel.setText("");
    }
    
    public void clearInputsCheckout() {
        nameList.setModel(new DefaultListModel());
        quantityList.setModel(new DefaultListModel());
        priceList.setModel(new DefaultListModel());
        reportProductID.setModel(new DefaultListModel());
        reportProductName.setModel(new DefaultListModel());
        reportProductSale.setModel(new DefaultListModel());
        reportProductRevenue.setModel(new DefaultListModel());
        
        subtotalLabel.setText("");
        totalLabel.setText("");
        productIDField.setText("");
        quantityField.setText("");
        homeNoticeLabel.setText("");
    }
    
    public void changeInputsUpdate(Boolean show) {
        homeNoticeLabel.setText("");
        updateNameField.setVisible(show);
        updateNameLabel.setVisible(show);
        updatePriceField.setVisible(show);
        updatePriceLabel.setVisible(show);
        updateVendorField.setVisible(show);
        updateVendorLabel.setVisible(show);
        updateTaxField.setVisible(show);
        updateTaxLabel.setVisible(show);
        updateWeightField.setVisible(show);
        updateWeightLabel.setVisible(show);
        if (!show) {
            updateNameField.setText("");
            updatePriceField.setText("");
            updateVendorField.setText("");
            updateTaxField.setText("");
            updateWeightField.setText("");
            updateSearchField.setText("");
        }
    }
    
   /* public void addInputsReset() {
        productIdField.setText("ID");
        productNameField.setText("Name");
        productPriceField.setText("Price");
        productVendorField.setText("Vendor");
        productWeightField.setText("Weight");
        productTaxField.setText("Tax");
        addAProductWarning.setVisible(false);
    }*/
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addContainer;
    private javax.swing.JLabel addHeaderLabel;
    private javax.swing.JTextField addNameField;
    private javax.swing.JLabel addNoticeLabel;
    private javax.swing.JTextField addPriceField;
    private javax.swing.JTextField addTaxField;
    private javax.swing.JTextField addVendorField;
    private javax.swing.JTextField addWeightField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButtonCheck;
    private javax.swing.JButton backButtonUpd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel checkAddItem;
    private javax.swing.JLabel checkHead;
    private javax.swing.JLabel checkName;
    private javax.swing.JLabel checkPrice;
    private javax.swing.JLabel checkProductIDLabel;
    private javax.swing.JLabel checkQuantity;
    private javax.swing.JLabel checkQuantityLabel;
    private javax.swing.JLabel checkSubLabel;
    private javax.swing.JLabel checkTotalLabel;
    private javax.swing.JButton checkoutAddButton;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JPanel checkoutContainer;
    private javax.swing.JLabel errorLabelCheckout;
    private javax.swing.JPanel homeContainer;
    private javax.swing.JLabel homeHeader;
    private javax.swing.JButton homeManagementButton;
    private javax.swing.JLabel homeNameLabel;
    private javax.swing.JLabel homeNoticeLabel;
    private javax.swing.JButton homeReportButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel loginContainer;
    private javax.swing.JLabel loginHeader;
    private javax.swing.JTextField loginNameField;
    private javax.swing.JLabel loginNameLabel;
    private javax.swing.JLabel loginNoticeLabel;
    private javax.swing.JPasswordField loginPassField;
    private javax.swing.JLabel loginPassLabel;
    private javax.swing.JButton loginSubmitButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JList<String> nameList;
    private javax.swing.JScrollPane nameScroll;
    private javax.swing.JList<String> priceList;
    private javax.swing.JScrollPane priceScroll;
    private javax.swing.JTextField productIDField;
    private javax.swing.JTextField quantityField;
    private javax.swing.JList<String> quantityList;
    private javax.swing.JScrollPane quantityScroll;
    private javax.swing.JButton reportBackButton;
    private javax.swing.JPanel reportContainer;
    private javax.swing.JLabel reportHeaderLabel;
    private javax.swing.JScrollPane reportIDPane;
    private javax.swing.JScrollPane reportNamePane;
    private javax.swing.JList<String> reportProductID;
    private javax.swing.JList<String> reportProductName;
    private javax.swing.JList<String> reportProductRevenue;
    private javax.swing.JList<String> reportProductSale;
    private javax.swing.JLabel reportRevenueLabel;
    private javax.swing.JScrollPane reportRevenuePane;
    private javax.swing.JLabel reportRevenueValue;
    private javax.swing.JScrollPane reportSalePane;
    private javax.swing.JComboBox<String> reportSortSelect;
    private javax.swing.JButton settingUpdateButton;
    private javax.swing.JButton settingsBackButton;
    private javax.swing.JPanel settingsContainer;
    private javax.swing.JLabel settingsHeader;
    private javax.swing.JLabel settingsNoticeLabel;
    private javax.swing.JPasswordField settingsPasswordField;
    private javax.swing.JLabel settingsPasswordLabel;
    private javax.swing.JTextField settingsProfileField;
    private javax.swing.JLabel settingsProfileLabel;
    private javax.swing.JLabel settingsProfilePic;
    private javax.swing.JLabel settingsProfilePicLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton submitButtonCheck;
    private javax.swing.JButton submitButtonUpd;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JPanel updateContainer;
    private javax.swing.JLabel updateErrorLabel;
    private javax.swing.JLabel updateFindLabel;
    private javax.swing.JLabel updateHeader;
    private javax.swing.JTextField updateNameField;
    private javax.swing.JLabel updateNameLabel;
    private javax.swing.JTextField updatePriceField;
    private javax.swing.JLabel updatePriceLabel;
    private javax.swing.JButton updateSearchButton;
    private javax.swing.JTextField updateSearchField;
    private javax.swing.JTextField updateTaxField;
    private javax.swing.JLabel updateTaxLabel;
    private javax.swing.JTextField updateVendorField;
    private javax.swing.JLabel updateVendorLabel;
    private javax.swing.JTextField updateWeightField;
    private javax.swing.JLabel updateWeightLabel;
    private javax.swing.JLabel userNoticeLabel;
    private javax.swing.JButton usersBackButton;
    private javax.swing.JPanel usersContainer;
    private javax.swing.JLabel usersDisclaimerLabel;
    private javax.swing.JLabel usersHeaderLabel;
    private javax.swing.JCheckBox usersManagerCheck;
    private javax.swing.JTextField usersNameField;
    private javax.swing.JLabel usersNameLabel;
    private javax.swing.JTextField usersProfilePicField;
    private javax.swing.JLabel usersProfilePicLabel;
    private javax.swing.JButton usersSubmitButton;
    // End of variables declaration//GEN-END:variables
}
